version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./:/var/www/html/"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./mysql:/var/lib/mysql/
    environment:
      POSTGRES_DB: supermarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password